### PR TITLE
elm-styled css

### PR DESCRIPTION
**Pull request by noformnocontent**
just an FYI, not sure if you would like it, feel free to dismiss

### CODE REVIEW

**Comment by xvw** [comment]
Yo ! Thanks for your contribution ! 
In fact, I do not really have an opinion on "this way of doing CSS" ... I'm not against (but not especially for). What is your opinion @phink?

**Comment by phink** [comment]
Hello @noformnocontent, thank you for your interest in Neige 🙂 
It's always a pleasure to have external contributions !

For my own part, I don't really see the point of using an Elm-like syntax in the CSS part (specially since this is a multi-language project) but I agree that it is always a good idea to use some formatter ! 

So if you can provide us with the one you used, I would accept this PR (if @xvw agrees too).

**Comment by noformnocontent** [comment]
no formatter, i just used a macros in sublime text

there is https://github.com/rtfeldman/elm-css which is obv a better long-term solution

**Comment by xvw** [comment]
Ok, thanks for your interest !

**Pull request closed without merging**
